version: '3'

networks:
  dbnet:
    driver: nat

services:
  db:
    image: mongo:4.0-windowsservercore-1803
    networks:
      - dbnet
  web:
    build: .
    ports:
     - "8080:8080"
    networks:
      - dbnet
    environment:
     - MONGODB_URIxx=mongodb://172.22.135.164:27017/test
     - MONGODB_URI=mongodb://db:27017/test
    depends_on: 
     - db 
    volumes:
     - C:\Users\panma\Documents\docker\hackathon-starter:C:\live
    restart: unless-stopped
     