FROM microsoft/dotnet:2.1.302-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./dotnetapp/
WORKDIR /app/dotnetapp
RUN dotnet restore

# copy and publish app and libraries
WORKDIR /app/
COPY /. ./dotnetapp/
WORKDIR /app/dotnetapp
RUN dotnet publish -c Debug -o out


FROM microsoft/dotnet:2.1.2-aspnetcore-runtime

WORKDIR /app
COPY --from=build /app/dotnetapp/out ./

CMD ["dotnet", "app/tasty-site.dll"]

